### PR TITLE
Changes to `openff-qcsubmit` to use `next` QCFractal

### PR DESCRIPTION
**Pull request by dotsdl**
## Description
The `next` major iteration of QCFractal is coming soon, and these changes are those necessary for QCSubmit to be used with it.

- [x] Easy (straightforward/syntax) fixes in `test_submissions`
- [x]  Figure out how to wire pcm back in in `test_submissions.py::test_optimization_submissions_with_pcm`
- [x]  Easy (straightforward/syntax) fixes in `test_datasets`
- [x]  Hard (info content/architecture) fixes in `test_datasets`
- [x]  Easy (straightforward/syntax) fixes in `tests/results/`
    - Note: An example of quadrupole info is in `records_and_molecules[0][0].properties['scf quadrupole']` after calling `records_and_molecules = collection.to_records()` on the COH single point set
- [x]  ~Why is `test_results.py::test_collection_from_server[BasicResultCollection-OpenFF BCC Refit Study COH v1.0-spec_1-91-191]` returning 190 results when it used to return 191?~ The spec names were lost and one of the two specs had an errored calc
- [x] Figure out a new way for maxiter and scf keywords to get in submissions. Previously these were added by the `QCSpec` class from `common_structures` (which has values for those as defaults)
- [x] Figure out how to do torsiondrive mocking in `test_results.py::test_to_records[collection2-record2]` 
- [ ] Re-add `find_existing` to `_BaseDataset.submit` (`datasets.py` around line 220) (or open an issue to do in a separate PR)
- [x] Un-ignore `tests/results`
- [x] Add pre-commit config back
- [ ] Rename specs in single point datasets (cc https://github.com/MolSSI/QCFractal/issues/739)
- [ ] Is s99f now unloadable via openmmforcefields?

Release notes
* Note that QCF record IDs now fail equality checks with str, but succeed with int. 
* QCSubmit's `dataset.get_qc_spec` method is gone now, including its kwarg `keyword_id` (it's not clear to me what this means or where it's used)
* OptimizationDataset driver is now `deferred` (used to be `gradient`)
* pcm is currently unstable, so the test is marked as xfail
* Many tests now just run short jobs instead of mocking data from the QCA server
* cmiles is now found on all `entries` created in new submissions
* All `to_records` methods now warn about entries with invalid cmiles and then exclude them from the returned values.
* `OptimizationDataset.to_basic_result_collection` will now warn if it's unable to find results with the desired driver and will exclude them from the returned values. 

Dev install instructions

```
mamba env create -n qcsubmit-dev -f basic.yaml
mamba install -c conda-forge -c openeye openeye-toolkits jupyterlab
mamba install -c conda-forge -c conda-forge/label/libint_dev psi4
```

In a different folder
```
git clone -b next git@github.com:MolSSI/QCFractal.git # really important to check out this branch directly, otherwise you'll get a bunch of empty folders preventing pip installation
cd QCFractal
pip install ./qcportal ./qcarchivetesting ./qcfractalcompute ./qcfractal
```

To prevent posgresql's "not enough shared memory" issue:
```
sudo sysctl -w kern.sysv.shmall=65536
sudo sysctl -w kern.sysv.shmmax=16777216
```

Finally in the openff-qcsubmit folder
```
pip install -e ./
```

When running pytest, sometimes I'll get a postgres issue about a temporary file path being too long. I can fix that by setting `--basetemp` in the pytest invocation to something short-ish:

```
pytest openff/qcsubmit/tests/test_submissions.py --basetemp="/Users/jeffreywagner/temp"  -vvvvv
```

QCF next docs: https://molssi.github.io/QCFractal/user_guide/records/base.html#qcportal.dataset_models.BaseDataset.submit

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by dotsdl** [comment]
Live testing with this PR: https://github.com/openforcefield/qca-dataset-submission-next-test/pull/4

**Comment by dotsdl** [comment]
@bennybp please push your changes here when you get a chance. Thanks!

**Comment by j-wags** [comment]
Currently having trouble getting tests running locally (I arbitrarily started at `test_submission`) - the snowflake fixture is complaining that postgres isn't configured. Looking elsewhere, it looks like [I don't need to run `qcfractal-server init-db` if the tests are just using snowflake](https://github.com/MolSSI/QCFractal/blob/next/.github/workflows/full_tests_snowflake.yml#L60), but I DO need to run it if I'm [testing a full server](https://github.com/MolSSI/QCFractal/blob/c7e4a327aa938c20fa2905ea8a7a4faec4272663/.github/workflows/full_tests.yml#L67) (which I don't think we're doing here):

```shell
===================================================================================== ERRORS ======================================================================================
___________________________________________________ ERROR at setup of test_basic_submissions_single_spec[PSI4 hf 3-21g energy] ____________________________________________________

tmp_path_factory = TempPathFactory(_given_basetemp=None, _trace=<pluggy._tracing.TagTracerSub object at 0x17516ce50>, _basetemp=PosixPath...s/v9/2_5kkyp10z37wvxz8b3rl6_h0000gn/T/pytest-of-jeffreywagner/pytest-11'), _retention_count=3, _retention_policy='all')

    @pytest.fixture(scope="session")
    def postgres_server(tmp_path_factory):
        """
        A postgres server instance
    
        This does not contain any databases (except the postgres defaults).
    
        This is built only once per session, and automatically deleted after the session. It uses
        a pytest-provided session-scoped temporary directory
        """
    
        db_path = str(tmp_path_factory.mktemp("db"))
>       test_pg = QCATestingPostgresServer(db_path)

../../../conda/envs/qcsubmit-test-basic/lib/python3.11/site-packages/qcarchivetesting/testing_fixtures.py:31: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../conda/envs/qcsubmit-test-basic/lib/python3.11/site-packages/qcarchivetesting/testing_classes.py:74: in __init__
    self.tmp_pg = TemporaryPostgres(data_dir=db_path)
../../../conda/envs/qcsubmit-test-basic/lib/python3.11/site-packages/qcfractal/postgres_harness.py:664: in __init__
    self._harness.initialize_postgres()
../../../conda/envs/qcsubmit-test-basic/lib/python3.11/site-packages/qcfractal/postgres_harness.py:544: in initialize_postgres
    self.start()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <qcfractal.postgres_harness.PostgresHarness object at 0x17516cc50>

    def start(self) -> None:
        """
        Starts a PostgreSQL server based off the current configuration parameters.
    
        The PostgreSQL server must be initialized and the configured port open. The database does not need to exist.
        """
    
        # We should only do this if we are in charge of the database itself
        assert self.config.own
    
        # Startup the server
        self._logger.info("Starting the PostgreSQL instance")
    
        # We should be in charge of this postgres process. If something is running, then that is a problem
        if is_port_inuse(self.config.host, self.config.port):
            raise RuntimeError(
                f"A process is already running on port {self.config.port} that is not associated with this QCFractal instance's database"
            )
        else:
            retcode, stdout, stderr = self.pg_ctl(["start"])
    
            err_msg = f"Error starting PostgreSQL. Did you remember to initialize it (qcfractal-server init)?\noutput:\n{stdout}\nstderr:\n{stderr}"
    
            if retcode != 0:
>               raise RuntimeError(err_msg)
E               RuntimeError: Error starting PostgreSQL. Did you remember to initialize it (qcfractal-server init)?
E               output:
E               waiting for server to start.... stopped waiting
E               
E               stderr:
E               pg_ctl: could not start server
E               Examine the log output.

../../../conda/envs/qcsubmit-test-basic/lib/python3.11/site-packages/qcfractal/postgres_harness.py:452: RuntimeError
```

**Comment by j-wags** [comment]
Hah, so my local snowflake failures were because of the following (from the postgres log):

```
E               log contents:
E               2023-07-05 11:24:07.864 PDT [47226] LOG:  starting PostgreSQL 15.3 on x86_64-apple-darwin13.4.0, compiled by clang version 15.0.7, 64-bit
E               2023-07-05 11:24:07.866 PDT [47226] LOG:  listening on IPv4 address "127.0.0.1", port 64387
E               2023-07-05 11:24:07.866 PDT [47226] LOG:  listening on IPv6 address "::1", port 64387
E               2023-07-05 11:24:07.866 PDT [47226] LOG:  Unix-domain socket path "/private/var/folders/v9/2_5kkyp10z37wvxz8b3rl6_h0000gn/T/pytest-of-jeffreywagner/pytest-19/db0/.s.PGSQL.64387" is too long (maximum 103 bytes)
E               2023-07-05 11:24:07.866 PDT [47226] WARNING:  could not create Unix-domain socket in directory "/private/var/folders/v9/2_5kkyp10z37wvxz8b3rl6_h0000gn/T/pytest-of-jeffreywagner/pytest-19/db0"
E               2023-07-05 11:24:07.866 PDT [47226] FATAL:  could not create any Unix-domain sockets
E               2023-07-05 11:24:07.866 PDT [47226] LOG:  database system is shut down
```

Adding `--basetemp=/Users/jeffreywagner/temp` to my pytest invocations solved this, now I get the same error as the GitHub CI.

**Comment by j-wags** [comment]
An evolving notes post (mostly for myself, will be editing this a lot)

* Big picture, I want to look into whether QCSubmit can drop its dataset classes and just use the new ones from QCFractal. QCSubmit's Factory classes could then just directly produce QCF datasets. 
* It'd be helpful if the QCATestingSnowflake class came with a worker or two. Right now it's [hard-coded at 0](https://github.com/MolSSI/QCFractal/blob/next/qcarchivetesting/qcarchivetesting/testing_classes.py#L165)
* I should update the tests to not [load molecules from PDB](https://github.com/openforcefield/openff-qcsubmit/blob/main/openff/qcsubmit/tests/test_submissions.py#L49)

**Comment by bennybp** [comment]
>     * I've been told that QCSubmit can now drop most/all of its caching functionality. I have yet to look into that/understand its current caching functionality.

There's some caching in datasets, but not much in the client. I do have a few todo items around there with saving the cache for later use.

>     * It'd be helpful if the QCATestingSnowflake class came with a worker or two. Right now it's [hard-coded at 0](https://github.com/MolSSI/QCFractal/blob/next/qcarchivetesting/qcarchivetesting/testing_classes.py#L165)

For your testing you might be able to get away with a plain `FractalSnowflake` rather than the testing one. Although I guess it depends on what tests you want. I can always add workers to the `QCATestingSnowflake`

**Comment by j-wags** [comment]
Thanks for the pointers @bennybp!

**Comment by j-wags** [comment]
I spoke with @mattwthompson yesterday and he pointed out that we should keep the QCSubmit dataset classes, since they're the only available dataset class that holds OFFMols natively, and he plans to use them for the internal benchmarking project.

**Comment by ntBre** [comment]
My last commit got the basic `test_optimization_submissions` passing, but I'm a bit stuck on `test_optimization_submissions_with_constraints`. It really looks like the constraints are not being propagated to the QCPortal stuff. I can push what I have so far if anyone is interested in seeing it, but I both can't find constraints in any of the `record.*.keywords` fields and the final angle measurements are failing. Is anyone more familiar with how QCPortal is handling constraints? Probably that's not even the right question to ask. I can't find anything in their `OptimizationRecord` or `OptimizationDataset` code that even mentions constraints.

**Comment by jthorton** [comment]
Hi @ntBre, Thanks for taking this on and for all the changes so far. I need to dig into this a little more but I think that the constraints are being missed by qcfractal. Here is my thought thread and I'll cc: @bennybp to make sure I am on the right lines.

For optimisation datasets where we need unique constraints for each molecule we store the constraints in the `additional_keywords` field which should be combined with the specification keywords to create each molecules unique task. I see that in the next branch the [OptimizationDatasetEntryORM](https://github.com/MolSSI/QCFractal/blob/d5aa7bb7f2d6fd9951c3d36852dad9ba7fdc41a4/qcfractal/qcfractal/components/optimization/dataset_db_models.py#L21) model still has this field. The [OptimizationRecordORM](https://github.com/MolSSI/QCFractal/blob/d5aa7bb7f2d6fd9951c3d36852dad9ba7fdc41a4/qcfractal/qcfractal/components/optimization/record_db_models.py#L91) model however does not, and it is this second model which is used to create the optimization task [here](https://github.com/MolSSI/QCFractal/blob/d5aa7bb7f2d6fd9951c3d36852dad9ba7fdc41a4/qcfractal/qcfractal/components/optimization/record_socket.py#L61C71-L61C71). To fix this I think the `OptimizationRecordORM` needs extending to include the `additional_keywords` and they then need to be combined with the opt_keywords [here](https://github.com/MolSSI/QCFractal/blob/d5aa7bb7f2d6fd9951c3d36852dad9ba7fdc41a4/qcfractal/qcfractal/components/optimization/record_socket.py#L72) before creating the task. @bennybp it would be great if you could check this I might have missed something trying to follow the new code!

**Comment by j-wags** [comment]
(From a meeting today) BP -- In the new QCFractal (which may differ in design philosophy from QCSubmit) the additional_keywords should start in the entry in the dataset, then running [dataset.submit should make OptimizationRecords where the additional_keywords get into each OptimizationRecord's specification](https://github.com/MolSSI/QCFractal/blob/d5aa7bb7f2d6fd9951c3d36852dad9ba7fdc41a4/qcfractal/qcfractal/components/singlepoint/dataset_socket.py#L106).

In today's debugging, QCSubmit's datasets.py line 1032 seems like the place where additional keywords should be propagated, looks like examples of previous propagation are around line 1406.

**Comment by jthorton** [comment]
Thats great following that I notice that we also need to pass the attributes to the each of the new dataset entry objects in each of the `_get_entries` methods.

**Comment by j-wags** [comment]
Temporarily unhooking `find_existing` kwarg from `_BaseDataset.submit` since it's not in a built QCFractal `next` package yet, so it's causing CI to fail. Added a to-do in PR body text so we don't forget.

**Comment by jthorton** [comment]
Thanks so much, everyone, fantastic to qcsumit back online!

**Pull request merged**
