### PR TITLE
Use Psi4 1.8

### PR DESCRIPTION
**Pull request by mattwthompson**

### CODE REVIEW

**Comment by jthorton** [comment]
Hey @mattwthompson thanks for looking into this, I think until Psi4 on conda-forge includes the fortran interface for PCM these tests will fail. We should keep an eye open for when this change happens but until then we need to use the psi4 channel.

**Comment by mattwthompson** [comment]
You seem to be correct: https://psicode.org/psi4manual/1.5.0/glossary_psivariables.html#psivar-SCF-DIPOLE

**Comment by mattwthompson** [comment]
The tests are running really, really slowly now: https://github.com/openforcefield/openff-qcsubmit/actions/runs/5554756531/jobs/10144963963

I haven't looked into why

**Comment by j-wags** [comment]
Superseded by the already-merged #218

**Pull request closed without merging**
