### PR TITLE
Toolkit 0.11 support

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
## Description

Update QCSubmit to work with the OpenFF Toolkit 0.11+

Supersedes #203 

## Todos
- [x] Pin Toolkit >= 0.11 in environments

Test failures (running locally on my machine):
  - [x] Many test failures due to moving from OpenMM units to OpenFF units in locally executed code that were fixed with simple find+replace
  - [x]  Several test failures due to https://github.com/openforcefield/openff-toolkit/issues/1416 that are fixed in https://github.com/openforcefield/openff-toolkit/pull/1417
  - [x] A usage of `pytest.approx` that needed updating with the new units package
  - [x] Manual unit handling in `combine_openff_molecules` around `np.vstack()` that is no longer necessary with OpenFF units
  - [x] A number of tests from QCEngine's lack of support for Toolkit 0.11 (https://github.com/MolSSI/QCEngine/pull/378)

## Status
- [x] Requires https://github.com/MolSSI/QCEngine/pull/378 in a release on conda forge
- [x] Requires https://github.com/openforcefield/openff-toolkit/pull/1417 in a release on conda forge
- [x] Ready to go

### CODE REVIEW

**Review by j-wags — APPROVED** [review]
Thanks @Yoshanuikabundi - Accepted pending passing tests. I also approve cutting a new release and making a new conda package based on this.

**Comment by jthorton** [comment]
@Yoshanuikabundi I noticed you have unpinned psi4 which is a great idea, I would recommend following this [environment](https://github.com/MolSSI/QCEngine/blob/master/devtools/conda-envs/psi.yaml) to get a psi4 version compatible with conda-forge. I think the important ones are 
- libint2=*=hc9558a2_9
- intel-openmp!=2019.5
- psi4=1.5
Happy to help out with getting it working as well!

**Comment by jthorton** [comment]
Ahh looks like the channel priority might need to be updated as well I think 
- psi4
- conda-forge
- openeye 
should work

**Comment by Yoshanuikabundi** [comment]
Love it when an environment solves but doesn't work!

**Comment by jthorton** [comment]
> Love it when an environment solves but doesn't work!

That's half the fun of using Psi4!

**Comment by Yoshanuikabundi** [comment]
OK I think the remaining errors are just waiting on the upstream updates.

**Comment by jthorton** [comment]
Most of the errors seem related to qcengine. [This](https://github.com/openforcefield/openff-qcsubmit/actions/runs/3225937916/jobs/5278848098#step:7:501) error looks like something to do with the toolkit though did something change with the properties dictionary?

**Comment by Yoshanuikabundi** [comment]
Yeah,  `__deepcopy__` was implemented for performance reasons and had a bug, the fix is merged and will be in the next toolkit release. Writing this PR is how we learned that 😂

I can temporarily pin the appropriate branches in the CI environment to make sure it all works if you like? But I figured we may as well wait for the releases.

**Comment by jthorton** [comment]
> Yeah, __deepcopy__ was implemented for performance reasons and had a bug, the fix is merged and will be in the next toolkit release. Writing this PR is how we learned that 😂

Ahh thats great that you have a solution already! 

> But I figured we may as well wait for the releases.

Yeah happy to wait, just wanted to check it was fixed good job!

**Comment by mattwthompson** [comment]
I updated the environments to install against the versions one would expect to work, just in case they don't ... and they do!

I will make a toolkit release in the coming days. I'll check with MolSSI on the status of a QCEngine release.

**Comment by mattwthompson** [comment]
This is soft blocked by https://github.com/openforcefield/openff-units/pull/51 being in a release because the next QCEngine release will include some fixes for the new pint - though Lori's changes might be backwards-compatible

**Comment by mattwthompson** [comment]
Assuming the checks of ebc3b015bc729adf2c961ef7ca6ee75ccc279b18 pass, I'm going to go ahead and merge this and cut a release later today or tomorrow.

My commits were prodding along with changes to upstreams and [isolating a weird bug](https://github.com/openforcefield/openff-bespokefit/pull/202#issuecomment-1314112832) in the upstream packaging. They mostly cancel each other out, resulting in [no changes to the source code](https://github.com/openforcefield/openff-bespokefit/pull/202#issuecomment-1314112832). So I consider the earlier approval from @j-wags still valid here.

**Pull request merged**
