### PR TITLE
Removed chunked saves for entry submission; added performance hack for single point task submission

### PR DESCRIPTION
**Pull request by dotsdl**
## Description
This removes chunked calls to `dataset.save` as entries (molecules) are added to a given dataset as part of submission, as these are unnecessary and only serve to slow submission as the collection object grows with additional entries added.

We also added in a performance hack for single point `Dataset`s only, in which we only call `collection.save` on the first call for a given spec addition and then again after all tasks are generated. This saves repeated movement of the collection object, which is unchanged as tasks are generated over the course of the loop.

Requires a new release of QCFractal beyond the current 0.15.7 release, in particular MolSSI/QCFractal#705.

## Status
- [ ] Ready to go

### CODE REVIEW

**Comment by jthorton** [comment]
@dotsdl thanks for adding this speed up! Looks like we need a new version of qcfractal to test on do we know when we will have a realese?

**Comment by dotsdl** [comment]
@jthorton hopefully today!

**Comment by jthorton** [comment]
@dotsdl merged the other PR feel free to merge this one once tests pass

**Comment by dotsdl** [comment]
Thanks @jthorton! Merging!

**Pull request merged**
